CREATE TABLE IF NOT EXISTS invoices (
    id SERIAL PRIMARY KEY,
    user_id INT,
    api_key_prefix TEXT,
    invoice_number VARCHAR(50) UNIQUE NOT NULL,
    stripe_invoice_id VARCHAR(255) UNIQUE,
    subtotal_cents INT NOT NULL,
    tax_cents INT DEFAULT 0,
    discount_cents INT DEFAULT 0,
    total_cents INT NOT NULL,
    amount_paid_cents INT DEFAULT 0,
    amount_due_cents INT NOT NULL,
    currency VARCHAR(3) DEFAULT 'USD',
    status VARCHAR(20) NOT NULL,
    billing_period_start TIMESTAMPTZ NOT NULL,
    billing_period_end TIMESTAMPTZ NOT NULL,
    due_date TIMESTAMP NOT NULL,
    paid_at TIMESTAMP,
    voided_at TIMESTAMP,
    line_items JSONB NOT NULL,
    notes TEXT,
    invoice_pdf_url TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
