ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS current_plan_price_cents INT;
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS billing_cycle VARCHAR(20);
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS auto_renew BOOLEAN DEFAULT TRUE;
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS cancel_at_period_end BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS mrr_cents INT;
ALTER TABLE IF EXISTS subscriptions ADD COLUMN IF NOT EXISTS stripe_subscription_id VARCHAR(255);
