# Fixed monorepo deployment configuration
services:
- type: web
  name: deedpro-main-api
  env: python
  plan: free
  repo: https://github.com/easydeed/new-front
  branch: main
  rootDir: backend
  buildCommand: pip install -r requirements.txt
  startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
  envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: deedpro-db
  - key: ALLOWED_ORIGINS
    value: https://deedpro-frontend-new.vercel.app
  # Phase 3 Backend Services & Routes Configuration
  - key: DYNAMIC_WIZARD_ENABLED
    value: "false"
  - key: TEMPLATE_VALIDATION_STRICT
    value: "true"
  - key: PDF_GENERATION_TIMEOUT
    value: "30"
  - key: AI_ASSIST_TIMEOUT
    value: "15"
  - key: TITLEPOINT_TIMEOUT
    value: "10"
  - key: MAX_CONCURRENT_REQUESTS
    value: "5"
  - key: BACKEND_LOGGING_LEVEL
    value: "INFO" 