services:
  - type: web
    name: deedpro-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TITLEPOINT_API_KEY
        sync: false
      - key: GOOGLE_PLACES_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: https://deedpro-frontend-new.vercel.app,https://your-custom-domain.com
      - key: JWT_SECRET
        sync: false
      - key: RATE_LIMIT_REQUESTS_PER_MINUTE
        value: "100"
      - key: RATE_LIMIT_DAILY_COST_LIMIT
        value: "100.00"
    healthCheckPath: "/health"
    numInstances: 2
    plan: standard
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 10
      targetMemoryPercent: 70
      targetCPUPercent: 70
    autoDeploy: true
    branch: main

