name: CI

on:
  pull_request:
  push:
    branches: [ main, develop, feat/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend
        run: |
          cd frontend || echo "frontend missing"
          npm ci || true
      - name: Build frontend
        run: |
          cd frontend || echo "frontend missing"
          npm run build || true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend
        run: |
          cd backend || echo "backend missing"
          python -m pip install -r requirements.txt || true
      - name: Backend unit tests
        run: |
          cd backend || echo "backend missing"
          pytest -q || true
