name: DeedPro CI/CD
on: 
  push:
    branches: [ main, staging, full-pivot-and-fixes ]
  pull_request:
    branches: [ main ]

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd frontend && npm ci
      - name: Run tests
        run: cd frontend && npm run build
      
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: cd backend && pip install -r requirements.txt
      - name: Test import
        run: cd backend && python -c "import main; print('✅ Backend imports OK')"
